type summaryProps = {
  summary: string;
}

const SummaryCard = ({ summary }: summaryProps) => (
  <div className="bg-gray-100 p-4 rounded shadow mb-4">
    <p>{summary}</p>
    <p className="text-sm text-gray-500 mt-2 italic">Generated by Gemini AI</p>
  </div>
);

export default SummaryCard;
